In [2]:
import json
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import plotly.graph_objects as go
import numpy as np

In [3]:
with open("n100-id1.json",'r') as f:
    coords = json.load(f)

In [4]:
coords['1']

[[[0.265779500728, -0.0, 0.51920593343],
  [0.403119671789, -0.0, 0.470153444042],
  [0.520859015131, -0.0, 0.577775054535],
  [0.505089756564, -0.0, 0.685766866797],
  [0.294134165634, -0.0, 0.735314605598],
  [0.251581149947, -0.0, 0.695885675706]],
 [[0.348225833132, 0.256038420588, 0.703385724578],
  [0.321547783743, 0.276557945358, 0.643232535823],
  [0.246038615828, 0.212163895265, 0.624941005946],
  [0.243401612449, 0.149820810581, 0.698867978245],
  [0.274253326768, 0.158615889777, 0.728074665359]],
 [[0.32760404996, 0.244173379184, 0.52497262996],
  [0.253425990663, 0.19302969523, 0.54563316588],
  [0.246038615828, 0.212163895265, 0.624941005946],
  [0.321547783743, 0.276557945358, 0.643232535823],
  [0.355033387665, 0.291026209525, 0.606423647471]],
 [[0.492255915564, 0.206096558082, 0.673306771426],
  [0.505133638038, 0.228943237797, 0.573992757174],
  [0.408952472691, 0.287287028463, 0.622642963254],
  [0.411187932022, 0.263964643175, 0.688002510393]],
 [[0.505133638038, 0.

In [5]:
def face_mean(numeral: str, face_num: int):
    same_coords = []
    mean_coord = []

    for j in range(0,3):
        for i in range(0, len(coords[numeral][face_num])):
            same_coords.append(coords[numeral][face_num][i][j])
        mean_coord.append(sum(same_coords)/len(coords[numeral][face_num]))
        same_coords = []

    return np.array(mean_coord)

In [6]:
coords_for_normal = []
for i in range(0, len(coords['1'])):
    coords_for_normal.append(coords['1'][i][0:3])
coords_for_normal
point1 = np.array(coords_for_normal[1][0])
point2 = np.array(coords_for_normal[1][1])
point3 = np.array(coords_for_normal[1][2])

    # Calculate two vectors
vector1 = point2 - point1
vector2 = point3 - point1

    # Find the cross product to get the normal vector
normal_vector = np.cross(vector1, vector2)

print(normal_vector)

[-0.00424884  0.00405413  0.00326732]


In [7]:
coords_for_normal

[[[0.265779500728, -0.0, 0.51920593343],
  [0.403119671789, -0.0, 0.470153444042],
  [0.520859015131, -0.0, 0.577775054535]],
 [[0.348225833132, 0.256038420588, 0.703385724578],
  [0.321547783743, 0.276557945358, 0.643232535823],
  [0.246038615828, 0.212163895265, 0.624941005946]],
 [[0.32760404996, 0.244173379184, 0.52497262996],
  [0.253425990663, 0.19302969523, 0.54563316588],
  [0.246038615828, 0.212163895265, 0.624941005946]],
 [[0.492255915564, 0.206096558082, 0.673306771426],
  [0.505133638038, 0.228943237797, 0.573992757174],
  [0.408952472691, 0.287287028463, 0.622642963254]],
 [[0.505133638038, 0.228943237797, 0.573992757174],
  [0.492255915564, 0.206096558082, 0.673306771426],
  [0.505089756564, -0.0, 0.685766866797]],
 [[0.32760404996, 0.244173379184, 0.52497262996],
  [0.253425990663, 0.19302969523, 0.54563316588],
  [0.265779500728, -0.0, 0.51920593343]],
 [[0.505133638038, 0.228943237797, 0.573992757174],
  [0.408952472691, 0.287287028463, 0.622642963254],
  [0.355033387

In [8]:
def normals_for_faces(numeral: str):
    coords_for_normal = []
    for i in range(0, len(coords[numeral])):
        coords_for_normal.append(coords[numeral][i][0:3])
    
    normals = []
    merged = []
    for i in range(0, len(coords_for_normal)):
        point1 = np.array(coords_for_normal[i][0])
        point2 = np.array(coords_for_normal[i][1])
        point3 = np.array(coords_for_normal[i][2])

        vector1 = point2 - point1
        vector2 = point3 - point1

        normal_vector = np.cross(vector1, vector2)

        merged_array = np.concatenate((face_mean(numeral, i), normal_vector))
        merged.append(merged_array)

        normals.append(normal_vector)

    return merged

In [9]:
normals_for_faces('1')[0][0:3]

array([0.37342721, 0.        , 0.61401693])

In [10]:
face_mean('1', 11)

array([0.26584256, 0.07710918, 0.71453573])

0.286693434384, 0.2106393923138, 0.6797003819902

In [11]:
sum(coords['1'][1][0])/len(coords['1'][1][0])

0.43588332609933333

In [12]:
print(coords_for_normal[1][0])
print(coords_for_normal[1][1])
print(coords_for_normal[1][2])

[0.348225833132, 0.256038420588, 0.703385724578]
[0.321547783743, 0.276557945358, 0.643232535823]
[0.246038615828, 0.212163895265, 0.624941005946]


In [13]:
point1 = np.array(coords_for_normal[1][0])
point2 = np.array(coords_for_normal[1][1])
point3 = np.array(coords_for_normal[1][2])

# Calculate two vectors
vector1 = point2 - point1
vector2 = point3 - point1

# Find the cross product to get the normal vector
normal_vector = np.cross(vector1, vector2)

print(normal_vector)

[-0.00424884  0.00405413  0.00326732]


In [14]:
with open("all_edges_n100-id1.json",'r') as f:
    edges = json.load(f)

In [15]:
import plotly.graph_objects as go

# Create traces for points and lines
traces = []
for points in coords['1']:
    x, y, z = zip(*points)
    trace_points = go.Scatter3d(x=x, y=y, z=z, mode='markers', marker=dict(size=5))
    traces.append(trace_points)

for edge in edges['1']:
    x, y, z = zip(*edge)
    trace_lines = go.Scatter3d(x=x, y=y, z=z, mode='lines', line=dict(color='red', width=2))
    traces.append(trace_lines)

# Create the figure
fig = go.Figure(data=traces)

# Set layout options
fig.update_layout(scene=dict(aspectmode='data'))

# Show the interactive plot
fig.show()

### 1. Берём первые 3 координаты
### 2. Считаем нормальный вектор
### 3. Смещаем координаты по нормальному вектору

In [16]:
# Define the vectors
vectors = normals_for_faces('1') # Example vectors

# Create traces for points, lines, and vectors
traces = []
for points in coords['1']:
    x, y, z = zip(*points)
    trace_points = go.Scatter3d(x=x, y=y, z=z, mode='markers', marker=dict(size=5))
    traces.append(trace_points)


for edge in edges['1']:
    x, y, z = zip(*edge)
    trace_lines = go.Scatter3d(x=x, y=y, z=z, mode='lines', line=dict(color='red', width=2))
    traces.append(trace_lines)

for vector in vectors:
    x, y, z, u, v, w = vector
    trace_vector = go.Cone(x=[x], y=[y], z=[z], u=[u], v=[v], w=[w], showscale=False, colorscale='Blues', sizemode='absolute', sizeref=0.05)
    traces.append(trace_vector)

trace_point = go.Scatter3d(x=[0.36866584416975], y=[0.15809395071000001],z=[0.6171869799346],mode = 'markers',
                           marker=dict(size=5,color='green'))

traces.append(trace_point)

# Create the figure
fig = go.Figure(data=traces)

# Set layout options
fig.update_layout(scene=dict(aspectmode='data'))

# Show the interactive plot
fig.show()

#### 4. Направить все нормали во внутрь


In [17]:
flattened_array = [item for sublist in coords['1'] for item in sublist]

# Remove duplicates
unique_array = [list(t) for t in {tuple(element) for element in flattened_array}]

unique_array

[[0.411187932022, 0.263964643175, 0.688002510393],
 [0.505133638038, 0.228943237797, 0.573992757174],
 [0.265779500728, -0.0, 0.51920593343],
 [0.355033387665, 0.291026209525, 0.606423647471],
 [0.32760404996, 0.244173379184, 0.52497262996],
 [0.492255915564, 0.206096558082, 0.673306771426],
 [0.505089756564, -0.0, 0.685766866797],
 [0.274253326768, 0.158615889777, 0.728074665359],
 [0.243401612449, 0.149820810581, 0.698867978245],
 [0.251581149947, -0.0, 0.695885675706],
 [0.520859015131, -0.0, 0.577775054535],
 [0.253425990663, 0.19302969523, 0.54563316588],
 [0.321547783743, 0.276557945358, 0.643232535823],
 [0.510589918935, 0.209039019291, 0.546318248671],
 [0.246038615828, 0.212163895265, 0.624941005946],
 [0.408952472691, 0.287287028463, 0.622642963254],
 [0.294134165634, -0.0, 0.735314605598],
 [0.348225833132, 0.256038420588, 0.703385724578],
 [0.403119671789, -0.0, 0.470153444042],
 [0.435103146144, 0.185122281884, 0.479843414404]]

In [18]:
same_coords = []
mean_coord = []

for j in range(0,3):
    for i in range(0, len(unique_array)):
        same_coords.append(unique_array[i][j])
    mean_coord.append(sum(same_coords)/len(unique_array))
    same_coords = []
mean_coord

[0.36866584416975, 0.15809395071000001, 0.6171869799346]

In [19]:
def mean_poly(numeral):
    flattened_array = [item for sublist in coords[numeral] for item in sublist]

    # Remove duplicates
    unique_array = [list(t) for t in {tuple(element) for element in flattened_array}]

    same_coords = []
    mean_coord = []

    for j in range(0,3):
        for i in range(0, len(unique_array)):
            same_coords.append(unique_array[i][j])
        mean_coord.append(sum(same_coords)/len(unique_array))
        same_coords = []
    
    return mean_coord

In [20]:
mean_poly('1')

[0.36866584416975, 0.15809395071000001, 0.6171869799346]

In [21]:
normals_for_faces('1')[0][0:3] - np.array([0.36866584416975, 0.15809395071000001, 0.6171869799346])

array([ 0.00476137, -0.15809395, -0.00317005])

In [22]:
normals_for_faces('1')[0][3:6]

array([ 0.        , -0.02055618,  0.        ])

In [23]:
np.dot(normals_for_faces('1')[0][3:6], np.array([ 0.00476137, -0.15809395, -0.00317005]))

0.0032498074219486483

In [24]:
-np.array([0.00476137, -0.15809395, -0.00317005])

array([-0.00476137,  0.15809395,  0.00317005])

In [25]:
np.dot(np.array([-0.00476137, 0.15809395, 0.00317005]), np.array([0.36866584416975, 0.15809395071000001, 0.6171869799346]))

0.025194856234136365

In [26]:
def normals_inside(face_num, poly_centre):

    centre_vector = normals_for_faces('1')[face_num][0:3] - poly_centre

    dot_product = np.dot(normals_for_faces('1')[face_num][3:6], centre_vector)

    if dot_product > 0:
        return np.concatenate((normals_for_faces('1')[face_num][0:3],-normals_for_faces('1')[face_num][3:6]))
    else:
        return np.concatenate((normals_for_faces('1')[face_num][0:3], normals_for_faces('1')[face_num][3:6]))

In [27]:
normals_for_faces('1')[0][0:3]

array([0.37342721, 0.        , 0.61401693])

In [28]:
normals_inside(0, np.array([0.36866584416975, 0.15809395071000001, 0.6171869799346]))

array([ 0.37342721,  0.        ,  0.61401693, -0.        ,  0.02055618,
       -0.        ])

#### Add face centre

In [29]:
normals_inside(1, np.array([0.36866584416975, 0.15809395071000001, 0.6171869799346]))

array([ 0.28669343,  0.21063939,  0.67970038,  0.00424884, -0.00405413,
       -0.00326732])

In [30]:
len(coords['1'])

12

In [31]:
# Define the vectors
#vectors = normals_for_faces('1') # Example vectors
vectors= []
mean_point = mean_poly('1')
for i in range(0, len(coords['1'])):
    vectors.append(normals_inside(i, mean_point))

# Create traces for points, lines, and vectors
traces = []
for points in coords['1']:
    x, y, z = zip(*points)
    trace_points = go.Scatter3d(x=x, y=y, z=z, mode='markers', marker=dict(size=5))
    traces.append(trace_points)


for edge in edges['1']:
    x, y, z = zip(*edge)
    trace_lines = go.Scatter3d(x=x, y=y, z=z, mode='lines', line=dict(color='red', width=2))
    traces.append(trace_lines)

for vector in vectors:
    x, y, z, u, v, w = vector
    trace_vector = go.Cone(x=[x], y=[y], z=[z], u=[u], v=[v], w=[w], showscale=False, colorscale='Blues', sizemode='absolute', sizeref=0.05)
    traces.append(trace_vector)

trace_point = go.Scatter3d(x = [mean_point[0]],y = [mean_point[1]], z = [mean_point[2]],mode = 'markers',
                           marker=dict(size=5,color='green'))

traces.append(trace_point)

# Create the figure
fig = go.Figure(data=traces)

# Set layout options
fig.update_layout(scene=dict(aspectmode='data'))

# Show the interactive plot
fig.show()

#### 5. Сдвинуть координаты на дистанцию

In [63]:
all_coords = []
for i in range(0, len(coords['1'])) :
    print("Coords:\n",coords['1'][i])
    print("Normals:\n",normals_inside(i, mean_point)[3:6])
    moved_points = []
    moved_faces = []
    for point in coords['1'][i]:
        
        #print(str(i),np.array(point) - 100*normals_inside(i, mean_point)[3:6])
        moved_faces.append(np.array(point) + normals_inside(i, mean_point)[3:6])
        #print(moved_faces)
    moved_points.append(moved_faces)
    print("Moved:\n", moved_points)
    all_coords.append(moved_faces)
    moved_faces = []
    

Coords:
 [[0.265779500728, -0.0, 0.51920593343], [0.403119671789, -0.0, 0.470153444042], [0.520859015131, -0.0, 0.577775054535], [0.505089756564, -0.0, 0.685766866797], [0.294134165634, -0.0, 0.735314605598], [0.251581149947, -0.0, 0.695885675706]]
Normals:
 [-0.          0.02055618 -0.        ]
Moved:
 [[array([0.2657795 , 0.02055618, 0.51920593]), array([0.40311967, 0.02055618, 0.47015344]), array([0.52085902, 0.02055618, 0.57777505]), array([0.50508976, 0.02055618, 0.68576687]), array([0.29413417, 0.02055618, 0.73531461]), array([0.25158115, 0.02055618, 0.69588568])]]
Coords:
 [[0.348225833132, 0.256038420588, 0.703385724578], [0.321547783743, 0.276557945358, 0.643232535823], [0.246038615828, 0.212163895265, 0.624941005946], [0.243401612449, 0.149820810581, 0.698867978245], [0.274253326768, 0.158615889777, 0.728074665359]]
Normals:
 [ 0.00424884 -0.00405413 -0.00326732]
Moved:
 [[array([0.35247467, 0.25198429, 0.7001184 ]), array([0.32579662, 0.27250381, 0.63996522]), array([0.25028

In [46]:
all_coords

[[array([ 2.65779501e-01, -2.05561783e-04,  5.19205933e-01]),
  array([ 4.03119672e-01, -2.05561783e-04,  4.70153444e-01]),
  array([ 5.20859015e-01, -2.05561783e-04,  5.77775055e-01]),
  array([ 5.05089757e-01, -2.05561783e-04,  6.85766867e-01]),
  array([ 2.94134166e-01, -2.05561783e-04,  7.35314606e-01]),
  array([ 2.51581150e-01, -2.05561783e-04,  6.95885676e-01])],
 [array([0.34818334, 0.25607896, 0.7034184 ]),
  array([0.3215053 , 0.27659849, 0.64326521]),
  array([0.24599613, 0.21220444, 0.62497368]),
  array([0.24335912, 0.14986135, 0.69890065]),
  array([0.27421084, 0.15865643, 0.72810734])],
 [array([0.32755954, 0.24423068, 0.52495466]),
  array([0.25338148, 0.193087  , 0.54561519]),
  array([0.2459941 , 0.2122212 , 0.62492303]),
  array([0.32150327, 0.27661525, 0.64321456]),
  array([0.35498887, 0.29108351, 0.60640568])],
 [array([0.49232497, 0.20618581, 0.67333626]),
  array([0.5052027 , 0.22903249, 0.57402224]),
  array([0.40902153, 0.28737628, 0.62267245]),
  array([0.411

In [38]:
len(coords['1'])

12

In [64]:
# Define the vectors
#vectors = normals_for_faces('1') # Example vectors
vectors= []
mean_point = mean_poly('1')
for i in range(0, len(coords['1'])):
    vectors.append(normals_inside(i, mean_point))

# Create traces for points, lines, and vectors
traces = []
for points in all_coords:
    x, y, z = zip(*points)
    trace_points = go.Scatter3d(x=x, y=y, z=z, mode='markers', marker=dict(size=5))
    traces.append(trace_points)


for edge in edges['1']:
    x, y, z = zip(*edge)
    trace_lines = go.Scatter3d(x=x, y=y, z=z, mode='lines', line=dict(color='red', width=2))
    traces.append(trace_lines)

for vector in vectors:
    x, y, z, u, v, w = vector
    trace_vector = go.Cone(x=[x], y=[y], z=[z], u=[u], v=[v], w=[w], showscale=False, colorscale='Blues', sizemode='absolute', sizeref=0.05)
    traces.append(trace_vector)

#trace_point = go.Scatter3d(x = [mean_point[0]],y = [mean_point[1]], z = [mean_point[2]],mode = 'markers',
#                           marker=dict(size=5,color='green'))

traces.append(trace_point)

# Create the figure
fig = go.Figure(data=traces)

# Set layout options
fig.update_layout(scene=dict(aspectmode='data'))

# Show the interactive plot
fig.show()

### 6. Убрать дублирование